-- MySQL Script generated by MySQL Workbench
-- Sun Mar 31 19:53:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `role` VARCHAR(10) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room` (
  `id` BIGINT(20) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `amount` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`meeting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`meeting` (
  `id` BIGINT(20) NOT NULL,
  `dateOfTheBeginning` DATETIME NOT NULL,
  `dateOfTheEnd` DATETIME NOT NULL,
  `theme` VARCHAR(45) NULL DEFAULT NULL,
  `room` INT NULL DEFAULT NULL,
  `notifications` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `room_idx` (`room` ASC) VISIBLE,
  CONSTRAINT `room`
    FOREIGN KEY (`room`)
    REFERENCES `mydb`.`room` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_meeting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_meeting` (
  `user_id` BIGINT(20) NOT NULL,
  `meeting_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`user_id`, `meeting_id`),
  INDEX `fk_user_has_meeting_meeting1_idx` (`meeting_id` ASC) VISIBLE,
  INDEX `fk_user_has_meeting_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_meeting_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_meeting_meeting1`
    FOREIGN KEY (`meeting_id`)
    REFERENCES `mydb`.`meeting` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
